server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE  # Load balanced service ID
          predicates:
            - Path=/user/**,/staff/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE  # Load balanced service ID
          predicates:
            - Path=/rating/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE  # Load balanced service ID
          predicates:
            - Path=/hotel/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-21192889.okta.com/oauth2/default
    audience: api://default
    client-id: 0oagw7u85c2SRL5095d7
    client-secret: -G1Q16BPlSW06n5j7uuD3FSJpRS9h7-2QRawBlvRe5VdlsKuv2lYbFgJJZJIZnKp
    scopes: openid, profile, email, offline_access


